openapi: 3.0.3
info:
  title: "IPV Core Internal"
  description: "The internal api presented by IPV Core Back for use by IPV Core Front"
  version: "1.0.0"
paths:
  /request-config:
    get:
      description: "Returns details of all Credential Issuers (CRIs) configured for use with IPV Core"
      responses:
        200:
          description: "A list of cri configurations"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  type: object
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${IPVCredentialIssuerConfig.Arn}/invocations
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"
  /issued-credentials:
    get:
      description: "Debug endpoint - only used by core-front debug page to get a list of current retrieved crdentials for users journey"
      responses:
        200:
          description: "Map of retrieved cri credentials"
          content:
            application/json:
              schema:
                type: "object"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${IPVIssuedCredentials.Arn}/invocations
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"
  /ipv-session:
    post:
      description: "Creates a new ipv core-back session"
      responses:
        200:
          description: "The ipv sessionId"
          content:
            application/json:
              schema:
                type: "object"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${IPVSessionFunction.Arn}/invocations
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"
  /journey/cri/return:
    post:
      description: "Called when a user returns from a CRI and will be responsible for completing the OAuth Requests with the cri and retrieveing the verifiable credential"
      responses:
        200:
          description: "Returns a redirect journeyResponse of '/journey/next'"
          content:
            application/jose:
              schema:
                $ref: "#/components/schemas/journeyResponse"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${IPVCriReturnFunction.Arn}/invocations
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"
  /journey/session/end:
    post:
      description: "Called when the user has completed their user journey in IPV Core"
      responses:
        200:
          description: "Authorization Code and details"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/journeyResponse"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${IPVSessionEndFunction.Arn}/invocations
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"
  /journey/{journeyStep}:
    post:
      description: Called when the user selects a journey event.
      responses:
        200:
          description: "Returns either a redirect journey eventResponse or a page eventResponse "
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/journeyResponse"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${IPVJourneyEngineFunction.Arn}/invocations
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"
  /shared-attributes:
    get:
      description: "Request the current shared attributes that have been gathered"
      responses:
        200:
          description: "The shared attribute JWT"
          content:
            application/jwt:
              schema:
                type: "string"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${IPVSharedAttributesFunction.Arn}/invocations
        passthroughBehavior: "when_no_match"
        type: "aws_proxy"

components:
  schemas:
    journeyResponse:
      type: object
      properties:
        page:
          type: string
          description: pageId of page to be displayed
        journey:
          type: string
          description: journeyId of an journey to take
        cri:
          type: object
          description: redirect to a cri (credential issuer)
          required: [ "id", "authorizeUrl", "request" ]
          properties:
            id:
              type: string
            authorizeUrl:
              type: string
            request:
              type: string
        client:
          type: object
          description: redirect to the oauth client, ending the session.
          required: [ "callbackUrl", "authcode" ]
          properties:
            callbackUrl:
              type: string
            authcode:
              type: string
      oneOf:
        - required: [ "page" ]
        - required: [ "client" ]
        - required: [ "cri" ]
        - required: [ "journey" ]
