AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  step-function-spike

Resources:

  SimpleStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: EXPRESS
      Logging:
        Level: "ALL"
        Destinations:
          - CloudWatchLogsLogGroup:
              LogGroupArn: !GetAtt StateMachineLogGroup.Arn
        IncludeExecutionData: true
      DefinitionUri: state-machine/simple.asl.json
      DefinitionSubstitutions:
        MultiplyFunction: !GetAtt MultiplyFunction.Arn
        SquareFunction: !GetAtt SquareFunction.Arn
        AddFunction: !GetAtt AddFunction.Arn
        BiggerThanFunction: !GetAtt BiggerThanFunction.Arn
        IsItEvenFunction: !GetAtt IsItEvenFunction.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref MultiplyFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref SquareFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref AddFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref BiggerThanFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref IsItEvenFunction
        - Statement:
          - Sid: GeneralCloudWatchLogPolicy
            Effect: Allow
            Action:
              - logs:CreateLogDelivery
              - logs:CreateLogGroup
              - logs:DeleteLogDelivery
              - logs:DescribeResourcePolicies
              - logs:GetLogDelivery
              - logs:ListLogDeliveries
              - logs:PutResourcePolicy
              - logs:UpdateLogDelivery
            Resource:
              # These actions do not support resource-level permissions.
              # Policies granting access must specify "*" in the resource element.
              - "*"
        - Statement:
          - Sid: SpecificCloudWatchLogPolicy
            Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:DescribeLogGroups
              - logs:DescribeLogStreams
              - logs:PutLogEvents
            Resource:
              # Need to restrict this to the specific log group but it
              # wasn't working so using * for now.
              - "*"

  StateMachineLogGroup:
    Type: "AWS::Logs::LogGroup"
    Properties:
      LogGroupName: "PYI-765-state-machine"
      RetentionInDays: 1

  MultiplyFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: "multiplyFunction"
      Handler: "index.handler"
      CodeUri: ./multiplyFunction
      Runtime: "nodejs12.x"

  SquareFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: "squareFunction"
      Handler: "index.handler"
      CodeUri: ./squareFunction
      Runtime: "nodejs12.x"

  AddFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: "addFunction"
      Handler: "index.handler"
      CodeUri: ./addFunction
      Runtime: "nodejs12.x"

  BiggerThanFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: "biggerThanFunction"
      Handler: "index.handler"
      CodeUri: ./biggerThanFunction
      Runtime: "nodejs12.x"

  IsItEvenFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: "isItEvenFunction"
      Handler: "index.handler"
      CodeUri: ./isItEvenFunction
      Runtime: "nodejs12.x"

##########################################################################
#   HTTP API                                                             #
##########################################################################

  HttpApiforSyncWF:
    Type: AWS::Serverless::HttpApi
    Properties:
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: 'api.yaml'

#  ApiforSyncWF:
#    Type: AWS::Serverless::Api
#    Properties:
#      StageName: 'dev'
#      DefinitionBody:
#        'Fn::Transform':
#          Name: 'AWS::Include'
#          Parameters:
#            Location: 'api_2.yaml'

##########################################################################
#   Roles                                                               #
##########################################################################
  HttpApiRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - apigateway.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
      - PolicyName: AllowSFNExec
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action: "states:StartSyncExecution"
              Resource: !GetAtt SimpleStateMachine.Arn
