version = 0.1


[dev.deploy.parameters]
stack_name = "ipv-core-back-development"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "ipv-core-back-development"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
tags = "Service=\"di-ipv-core-back\""

[dev-tomw.deploy.parameters]
stack_name = "tom-core-back-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "tom-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-tomw\""
tags = "Service=\"di-ipv-core-back\""

[dev-danh.deploy.parameters]
stack_name = "danh-core-back-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "danh-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-danh\""
tags = "Service=\"di-ipv-core-back\""

[dev-danw.deploy.parameters]
stack_name = "danw-core-back-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "danw-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-danw\""
tags = "Service=\"di-ipv-core-back\""

[dev-danp.deploy.parameters]
stack_name = "danp-core-back-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "danp-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-danp\""
tags = "Service=\"di-ipv-core-back\""

[dev-chris.deploy.parameters]
stack_name = "chris-core-back-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "chris-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-chris\""
tags = "Service=\"di-ipv-core-back\""

[dev-amrit.deploy.parameters]
stack_name = "amrit-core-back-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "amrit-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-amrit\""
tags = "Service=\"di-ipv-core-back\""

[dev-lai.deploy.parameters]
stack_name = "lai-core-back-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "lai-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-lai\""
tags = "Service=\"di-ipv-core-back\""

[dev-sunil.deploy.parameters]
stack_name = "sunil-core-back-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "sunil-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-sunil\""
tags = "Service=\"di-ipv-core-back\""

[dev-kerr.deploy.parameters]
stack_name = "kerr-core-back-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "kerr-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-kerr\""
tags = "Service=\"di-ipv-core-back\""

[dev-philp.deploy.parameters]
stack_name = "philp-core-back-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "philp-core-back-stack"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev-philp\""
tags = "Service=\"di-ipv-core-back\""

