version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "philm-sam-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ec647gpjuo2w"
s3_prefix = "philm-sam-test"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
