AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ipv-core-back

Globals:
  Function:
    Timeout: 40
    Environment:
      Variables:
        JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1

Parameters:
  Environment:
    Type: String

Resources:

  IPVCoreInternalAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub IPV Core Internal API Gateway ${Environment}
      StageName: !Sub ${Environment}
      DefinitionBody:
        'Fn::Transform':
          Name: "AWS::Include"
          Parameters:
            Location: "../openAPI/core-back-internal.yaml"

  IPVCoreExternalAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub IPV Core External API Gateway ${Environment}
      StageName: !Sub ${Environment}
      DefinitionBody:
        'Fn::Transform':
          Name: "AWS::Include"
          Parameters:
            Location: "../openAPI/core-back-external.yaml"

  IPVSharedAttributesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "ipv-shared-attributes-${Environment}"
      Handler: uk.gov.di.ipv.core.sharedattributes.SharedAttributesHandler::handleRequest
      Runtime: java11
      PackageType: Zip
      CodeUri: ../lambdas/sharedattributes
      Architectures:
        - x86_64
      MemorySize: 512
      Tracing: Active
      Environment:
        Variables:
          ENVIRONMENT: !Sub "${Environment}"
          POWERTOOLS_SERVICE_NAME: !Sub shared-attributes-${Environment}
          USER_ISSUED_CREDENTIALS_TABLE_NAME: !Select [1, !Split ['/', !GetAtt UserIssuedCredentialsTable.Arn]]
          SIGNING_KEY_ID_PARAM: !Sub "/${Environment}/core/self/signingKeyId"
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UserIssuedCredentialsTable
        - SSMParameterReadPolicy:
            ParameterName: !Sub ${Environment}/core/self/signingKeyId
        - Statement:
          - Sid: kmsSigningKeyPermission
            Effect: Allow
            Action:
              - 'kms:sign'
            Resource:
              - !ImportValue SigningKeyArn
      Events:
        IPVCoreInternalAPI:
          Type: Api
          Properties:
            RestApiId: !Ref IPVCoreInternalAPI
            Path: /shared-attributes
            Method: GET

  IPVAccessTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "ipv-access-token-${Environment}"
      Handler: uk.gov.di.ipv.core.accesstoken.AccessTokenHandler::handleRequest
      Runtime: java11
      PackageType: Zip
      CodeUri: ../lambdas/accesstoken
      Architectures:
        - x86_64
      MemorySize: 512
      Tracing: Active
      Environment:
        Variables:
          ENVIRONMENT: !Sub "${Environment}"
          POWERTOOLS_SERVICE_NAME: !Sub access-token-${Environment}
          AUTH_CODES_TABLE_NAME: !Select [1, !Split ['/', !GetAtt AuthCodesTable.Arn]]
          ACCESS_TOKENS_TABLE_NAME: !Select [1, !Split ['/', !GetAtt AccessTokensTable.Arn]]
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref AccessTokensTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AuthCodesTable
        - SSMParameterReadPolicy:
            ParameterName: !Sub ${Environment}/core/clients/*
        - SSMParameterReadPolicy:
            ParameterName: !Sub ${Environment}/core/self/audienceForClients
        - SSMParameterReadPolicy:
            ParameterName: !Sub ${Environment}/core/self/maxAllowedAuthClientTtl
      Events:
        IPVCoreExternalAPI:
          Type: Api
          Properties:
            RestApiId: !Ref IPVCoreExternalAPI
            Path: /token
            Method: POST

  IPVSessionEndFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "ipv-session-end-${Environment}"
      Handler: uk.gov.di.ipv.core.sessionend.SessionEndHandler::handleRequest
      Runtime: java11
      PackageType: Zip
      CodeUri: ../lambdas/sessionend
      Architectures:
        - x86_64
      MemorySize: 512
      Tracing: Active
      Environment:
        Variables:
          ENVIRONMENT: !Sub "${Environment}"
          POWERTOOLS_SERVICE_NAME: !Sub session-end-${Environment}
          AUTH_CODES_TABLE_NAME: !Select [1, !Split ['/', !GetAtt AuthCodesTable.Arn]]
          IPV_SESSIONS_TABLE_NAME: !Select [ 1, !Split [ '/', !GetAtt SessionsTable.Arn ] ]
      Policies:
        - DynamoDBWritePolicy:
            TableName: !Ref AuthCodesTable
        - DynamoDBReadPolicy:
            TableName: !Ref AuthCodesTable
        - DynamoDBReadPolicy:
            TableName: !Ref SessionsTable
        - SSMParameterReadPolicy:
              ParameterName: !Sub ${Environment}/core/*
      Events:
        IPVCoreInternalAPI:
          Type: Api
          Properties:
            RestApiId:
              Ref: IPVCoreInternalAPI
            Path: /journey/session/end
            Method: POST

  IPVSessionStartFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "ipv-session-start-${Environment}"
      Handler: uk.gov.di.ipv.core.session.IpvSessionStartHandler::handleRequest
      Runtime: java11
      PackageType: Zip
      CodeUri: ../lambdas/sessionstart
      Architectures:
        - x86_64
      MemorySize: 512
      Tracing: Active
      Environment:
        Variables:
          ENVIRONMENT: !Sub "${Environment}"
          POWERTOOLS_SERVICE_NAME: !Sub session-start-${Environment}
          IPV_SESSIONS_TABLE_NAME: !Select [1, !Split ['/', !GetAtt SessionsTable.Arn]]
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref SessionsTable
        - DynamoDBWritePolicy:
            TableName: !Ref SessionsTable
      Events:
        IPVCoreInternalAPI:
          Type: Api
          Properties:
            RestApiId:
              Ref: IPVCoreInternalAPI
            Path: /session/start
            Method: POST

  IPVCriReturnFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "ipv-credential-issuer-return-${Environment}"
      Handler: uk.gov.di.ipv.core.credentialissuerreturn.CredentialIssuerReturnHandler::handleRequest
      Runtime: java11
      PackageType: Zip
      CodeUri: ../lambdas/credentialissuerreturn
      Architectures:
        - x86_64
      MemorySize: 512
      Tracing: Active
      Environment:
        Variables:
          CREDENTIAL_ISSUERS_CONFIG_PARAM_PREFIX: !Sub "/${Environment}/core/credentialIssuers"
          USER_ISSUED_CREDENTIALS_TABLE_NAME: !Select [1, !Split ['/', !GetAtt UserIssuedCredentialsTable.Arn]]
          SIGNING_KEY_ID_PARAM: !Sub "/${Environment}/core/self/signingKeyId"
          ENVIRONMENT: !Sub "${Environment}"
          POWERTOOLS_SERVICE_NAME: !Sub cri-return-${Environment}
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UserIssuedCredentialsTable
        - SSMParameterReadPolicy:
            ParameterName: !Sub ${Environment}/core/credentialIssuers/*
        - SSMParameterReadPolicy:
            ParameterName: !Sub ${Environment}/core/credentialIssuers
        - SSMParameterReadPolicy:
            ParameterName: !Sub ${Environment}/core/self/signingKeyId
        - SSMParameterReadPolicy:
            ParameterName: !Sub ${Environment}/core/self/jwtTtlSeconds
        - SQSSendMessagePolicy:
            QueueName: !ImportValue AuditEventQueueName
        - Statement:
          - Sid: kmsSigningKeyPermission
            Effect: Allow
            Action:
              - 'kms:sign'
            Resource:
              - !ImportValue SigningKeyArn
      Events:
        IPVCoreInternalAPI:
          Type: Api
          Properties:
            RestApiId:
              Ref: IPVCoreInternalAPI
            Path: /journey/cri/return
            Method: POST

  IPVCredentialIssuerStartFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "ipv-credential-issuer-start-${Environment}"
      Handler: uk.gov.di.ipv.core.credentialissuer.CredentialIssuerStartHandler::handleRequest
      Runtime: java11
      PackageType: Zip
      CodeUri: ../lambdas/credentialissuerstart
      Architectures:
        - x86_64
      MemorySize: 3008
      Tracing: Active
      Environment:
        Variables:
          CREDENTIAL_ISSUERS_CONFIG_PARAM_PREFIX: !Sub "/${Environment}/core/credentialIssuers"
          ENVIRONMENT: !Sub "${Environment}"
          POWERTOOLS_SERVICE_NAME: !Sub credential-issuer-start-${Environment}
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: !Sub ${Environment}/core/credentialIssuers/*
        - SSMParameterReadPolicy:
            ParameterName: !Sub ${Environment}/core/credentialIssuers
      Events:
        IPVCoreInternalAPI:
          Type: Api
          Properties:
            RestApiId:
              Ref: IPVCoreInternalAPI
            Path: /journey/cri/start/{criId}
            Method: POST

  IPVCredentialIssuerErrorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "ipv-credential-issuer-error-${Environment}"
      Handler: uk.gov.di.ipv.core.credentialissuererror.CredentialIssuerErrorHandler::handleRequest
      Runtime: java11
      PackageType: Zip
      CodeUri: ../lambdas/credentialissuererror
      Architectures:
        - x86_64
      MemorySize: 3008
      Tracing: Active
      Environment:
        Variables:
          ENVIRONMENT: !Sub "${Environment}"
          POWERTOOLS_SERVICE_NAME: !Sub credential-issuer-error-${Environment}
          IPV_SESSIONS_TABLE_NAME: !Select [ 1, !Split [ '/', !GetAtt SessionsTable.Arn ] ]
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref SessionsTable
        - DynamoDBWritePolicy:
            TableName: !Ref SessionsTable
      Events:
        IPVCoreInternalAPI:
          Type: Api
          Properties:
            RestApiId:
              Ref: IPVCoreInternalAPI
            Path: /journey/cri/error
            Method: POST

  IPVUserIdentityFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "ipv-user-identity-${Environment}"
      Handler: uk.gov.di.ipv.core.useridentity.UserIdentityHandler::handleRequest
      Runtime: java11
      PackageType: Zip
      CodeUri: ../lambdas/useridentity
      Architectures:
        - x86_64
      MemorySize: 512
      Tracing: Active
      Environment:
        Variables:
          ENVIRONMENT: !Sub "${Environment}"
          POWERTOOLS_SERVICE_NAME: !Sub user-identity-${Environment}
          ACCESS_TOKENS_TABLE_NAME: !Select [1, !Split ['/', !GetAtt AccessTokensTable.Arn]]
          USER_ISSUED_CREDENTIALS_TABLE_NAME: !Select [1, !Split ['/', !GetAtt UserIssuedCredentialsTable.Arn]]
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UserIssuedCredentialsTable
        - DynamoDBWritePolicy:
            TableName: !Ref UserIssuedCredentialsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AccessTokensTable
      Events:
        IPVCoreExternalAPI:
          Type: Api
          Properties:
            RestApiId:
              Ref: IPVCoreExternalAPI
            Path: /user-identity
            Method: GET

  IPVCredentialIssuerConfig:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "credential-issuer-config-${Environment}"
      Handler: uk.gov.di.ipv.core.credentialissuerconfig.CredentialIssuerConfigHandler::handleRequest
      Runtime: java11
      PackageType: Zip
      CodeUri: ../lambdas/credentialissuerconfig
      Architectures:
        - x86_64
      MemorySize: 512
      Tracing: Active
      Environment:
        Variables:
          ENVIRONMENT: !Sub "${Environment}"
          POWERTOOLS_SERVICE_NAME: !Sub credential-issuer-config-${Environment}
          CREDENTIAL_ISSUERS_CONFIG_PARAM_PREFIX: !Sub "/${Environment}/core/credentialIssuers"
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: !Sub ${Environment}/core/credentialIssuers/*
        - SSMParameterReadPolicy:
            ParameterName: !Sub ${Environment}/core/credentialIssuers
      Events:
        IPVCoreInternalAPI:
          Type: Api
          Properties:
            RestApiId:
              Ref: IPVCoreInternalAPI
            Path: /request-config
            Method: GET

  IPVIssuedCredentials:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "issued-credentials-${Environment}"
      Handler: uk.gov.di.ipv.core.issuedcredentials.IssuedCredentialsHandler::handleRequest
      Runtime: java11
      PackageType: Zip
      CodeUri: ../lambdas/issuedcredentials
      Architectures:
        - x86_64
      MemorySize: 512
      Tracing: Active
      Environment:
        Variables:
          ENVIRONMENT: !Sub "${Environment}"
          POWERTOOLS_SERVICE_NAME: !Sub issued-credentials-${Environment}
          USER_ISSUED_CREDENTIALS_TABLE_NAME: !Select [1, !Split ['/', !GetAtt UserIssuedCredentialsTable.Arn]]
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UserIssuedCredentialsTable
        - DynamoDBWritePolicy:
            TableName: !Ref UserIssuedCredentialsTable
      Events:
        IPVCoreInternalAPI:
          Type: Api
          Properties:
            RestApiId:
              Ref: IPVCoreInternalAPI
            Path: /issued-credentials
            Method: GET

  IPVJourneyEngineFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "journey-engine-${Environment}"
      Handler: uk.gov.di.ipv.core.journeyengine.JourneyEngineHandler::handleRequest
      Runtime: java11
      PackageType: Zip
      CodeUri: ../lambdas/journeyengine
      Architectures:
        - x86_64
      MemorySize: 512
      Tracing: Active
      Environment:
        Variables:
          ENVIRONMENT: !Sub "${Environment}"
          POWERTOOLS_SERVICE_NAME: !Sub session-${Environment}
          IPV_SESSIONS_TABLE_NAME: !Select [ 1, !Split [ '/', !GetAtt SessionsTable.Arn ] ]
          IPV_JOURNEY_CRI_START_URI: "/journey/cri/start/"
          IPV_JOURNEY_SESSION_END_URI: "/journey/session/end"
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref SessionsTable
        - DynamoDBWritePolicy:
            TableName: !Ref SessionsTable
      Events:
        IPVCoreInternalAPI:
          Type: Api
          Properties:
            RestApiId:
              Ref: IPVCoreInternalAPI
            Path: /journey/{journeyStep}
            Method: POST

  UserIssuedCredentialsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "user-issued-credentials-${Environment}"
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: "ipvSessionId"
          AttributeType: "S"
        - AttributeName: "credentialIssuer"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ipvSessionId"
          KeyType: "HASH"
        - AttributeName: "credentialIssuer"
          KeyType: "RANGE"

  AuthCodesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "auth-codes-${Environment}"
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: "authCode"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "authCode"
          KeyType: "HASH"

  AccessTokensTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "access-tokens-${Environment}"
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: "accessToken"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "accessToken"
          KeyType: "HASH"

  SessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "sessions-${Environment}"
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: "ipvSessionId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ipvSessionId"
          KeyType: "HASH"

Outputs:
  IPVCoreInternalAPIGatewayID:
    Description: Core Back Internal API Gateway ID
    Export:
      Name: !Sub "${AWS::StackName}-IPVCoreInternalAPIGatewayID"
    Value: !Ref IPVCoreInternalAPI
  IPVCoreExternalAPIGatewayID:
    Description: Core Back External API Gateway ID
    Export:
      Name: !Sub "${AWS::StackName}-IPVCoreExternalAPIGatewayID"
    Value: !Ref IPVCoreExternalAPI
