AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ipv-core-back

Globals:
  Function:
    Timeout: 20

Parameters:
  Environment:
    Type: String

Resources:

  IPVCoreAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: IPV Core API Gateway
      StageName: !Sub ${Environment}

  IPVAccessTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "ipv-access-token-${Environment}"
      Handler: uk.gov.di.ipv.core.accesstoken.AccessTokenHandler::handleRequest
      Runtime: java11
      PackageType: Zip
      CodeUri: ../lambdas/accesstoken
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          AUTH_CODES_TABLE_NAME: !Select [1, !Split ['/', !GetAtt AuthCodesTable.Arn]]
          ACCESS_TOKENS_TABLE_NAME: !Select [1, !Split ['/', !GetAtt AccessTokensTable.Arn]]
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref AccessTokensTable
        - DynamoDBReadPolicy:
            TableName: !Ref AuthCodesTable
      Events:
        IPVCoreAPI:
          Type: Api
          Properties:
            RestApiId: !Ref IPVCoreAPI
            Path: /token
            Method: POST

  IPVAuthorizationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "ipv-authorization-${Environment}"
      CodeUri: IPVAuthorizationFunction
      Handler: uk.gov.di.ipv.core.authorization.AuthorizationHandler::handleRequest
      Runtime: java11
      PackageType: Zip
      CodeUri: ../lambdas/authorization
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          AUTH_CODES_TABLE_NAME: !Select [1, !Split ['/', !GetAtt AuthCodesTable.Arn]]
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref AuthCodesTable
      Events:
        IPVCoreAPI:
          Type: Api
          Properties:
            RestApiId:
              Ref: IPVCoreAPI
            Path: /authorize
            Method: POST

  IPVSessionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "ipv-session-${Environment}"
      CodeUri: IPVSessionFunction
      Handler: uk.gov.di.ipv.core.session.IpvSessionHandler::handleRequest
      Runtime: java11
      PackageType: Zip
      CodeUri: ../lambdas/session
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          IPV_SESSIONS_TABLE_NAME: !Select [1, !Split ['/', !GetAtt SessionsTable.Arn]]
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref SessionsTable
      Events:
        IPVCoreAPI:
          Type: Api
          Properties:
            RestApiId:
              Ref: IPVCoreAPI
            Path: /ipv-session
            Method: POST

  IPVCredentialIssuerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "ipv-credential-issuer-${Environment}"
      CodeUri: IPVCredentialIssuerFunction
      Handler: uk.gov.di.ipv.core.credentialissuer.CredentialIssuerHandler::handleRequest
      Runtime: java11
      PackageType: Zip
      CodeUri: ../lambdas/credentialissuer
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          CREDENTIAL_ISSUER_CONFIG_PARAMETER_STORE_KEY: "/Development/credential-issuers-config"
          USER_ISSUED_CREDENTIALS_TABLE_NAME: !Select [1, !Split ['/', !GetAtt UserIssuedCredentialsTable.Arn]]
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UserIssuedCredentialsTable
      Events:
        IPVCoreAPI:
          Type: Api
          Properties:
            RestApiId:
              Ref: IPVCoreAPI
            Path: /request-evidence
            Method: POST

  IPVUserIdentityFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "ipv-user-identity-${Environment}"
      CodeUri: IPVUserIdentityFunction
      Handler: uk.gov.di.ipv.core.useridentity.UserIdentityHandler::handleRequest
      Runtime: java11
      PackageType: Zip
      CodeUri: ../lambdas/useridentity
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          AUTH_CODES_TABLE_NAME: !Select [1, !Split ['/', !GetAtt AuthCodesTable.Arn]]
          USER_ISSUED_CREDENTIALS_TABLE_NAME: !Select [1, !Split ['/', !GetAtt UserIssuedCredentialsTable.Arn]]
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref UserIssuedCredentialsTable
        - DynamoDBReadPolicy:
            TableName: !Ref AuthCodesTable
      Events:
        IPVCoreAPI:
          Type: Api
          Properties:
            RestApiId:
              Ref: IPVCoreAPI
            Path: /user-identity
            Method: GET

  CredentialIssuerConfig:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "/${Environment}/credential-issuers-config"
      Type: "String"
      Value: "TestValue"

  UserIssuedCredentialsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "user-issued-credentials-${Environment}"
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: "ipvSessionId"
          AttributeType: "S"
        - AttributeName: "credentialIssuer"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ipvSessionId"
          KeyType: "HASH"
        - AttributeName: "credentialIssuer"
          KeyType: "RANGE"

  AuthCodesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "auth-codes-${Environment}"
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: "authCode"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "authCode"
          KeyType: "HASH"

  AccessTokensTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "access-tokens-${Environment}"
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: "accessToken"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "accessToken"
          KeyType: "HASH"

  SessionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "sessions-${Environment}"
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: "ipvSessionId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ipvSessionId"
          KeyType: "HASH"
