AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'step-function-spike

  '
Resources:
  SimpleStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Type: EXPRESS
      Logging:
        Level: ALL
        Destinations:
        - CloudWatchLogsLogGroup:
            LogGroupArn:
              Fn::GetAtt:
              - StateMachineLogGroup
              - Arn
        IncludeExecutionData: true
      DefinitionUri: ../../state-machine/simple.asl.json
      DefinitionSubstitutions:
        MultiplyFunction:
          Fn::GetAtt:
          - MultiplyFunction
          - Arn
        SquareFunction:
          Fn::GetAtt:
          - SquareFunction
          - Arn
      Policies:
      - LambdaInvokePolicy:
          FunctionName:
            Ref: MultiplyFunction
      - LambdaInvokePolicy:
          FunctionName:
            Ref: SquareFunction
      - Statement:
        - Sid: GeneralCloudWatchLogPolicy
          Effect: Allow
          Action:
          - logs:CreateLogDelivery
          - logs:CreateLogGroup
          - logs:DeleteLogDelivery
          - logs:DescribeResourcePolicies
          - logs:GetLogDelivery
          - logs:ListLogDeliveries
          - logs:PutResourcePolicy
          - logs:UpdateLogDelivery
          Resource:
          - '*'
      - Statement:
        - Sid: SpecificCloudWatchLogPolicy
          Effect: Allow
          Action:
          - logs:CreateLogStream
          - logs:DescribeLogGroups
          - logs:DescribeLogStreams
          - logs:PutLogEvents
          Resource:
          - '*'
  StateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: PYI-765-state-machine
      RetentionInDays: 1
  MultiplyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: multiplyFunction
      Handler: index.handler
      CodeUri: MultiplyFunction
      Runtime: nodejs12.x
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.MultiplyFunctionb8354af8DepLayer
    Metadata:
      SamResourceId: MultiplyFunction
  SquareFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: squareFunction
      Handler: index.handler
      CodeUri: SquareFunction
      Runtime: nodejs12.x
      Layers:
      - Fn::GetAtt:
        - AwsSamAutoDependencyLayerNestedStack
        - Outputs.SquareFunctiond87c11a6DepLayer
    Metadata:
      SamResourceId: SquareFunction
  HttpApiforSyncWF:
    Type: AWS::Serverless::HttpApi
    Properties:
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ../../api.yaml
  HttpApiRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - apigateway.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: AllowSFNExec
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action: states:StartSyncExecution
            Resource:
              Fn::GetAtt:
              - SimpleStateMachine
              - Arn
  AwsSamAutoDependencyLayerNestedStack:
    DeletionPolicy: Delete
    Metadata:
      CreatedBy: AWS SAM CLI sync command
    Properties:
      TemplateURL: /Users/dan.worth/projects/gds/di-ipv-core-back/step-function-spike/.aws-sam/auto-dependency-layer/nested_template.yaml
    Type: AWS::CloudFormation::Stack
